version: '3'

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gaeway
      dockerfile: dockerfile.prod
    image: us-east1-docker.pkg.dev/microservices-store-449702/registry-image/client-gateway-prd
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
  
  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: us-east1-docker.pkg.dev/microservices-store-449702/registry-image/auth-ms-prd
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: us-east1-docker.pkg.dev/microservices-store-449702/registry-image/products-ms-prod
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: us-east1-docker.pkg.dev/microservices-store-449702/registry-image/orders-ms-prd
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}



  payments-ms:
    container_name: payments-ms
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: us-east1-docker.pkg.dev/microservices-store-449702/registry-image/payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINTSECRET=${STRIPE_ENDPOINTSECRET}
