apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/microservices-store-449702/registry-image/products-ms-prod
        name: products-ms-prd
        env:
        - name: DATABASE_URL
          value: "file:./dev.db"
        - name: NATS_SERVERS
          value: "nats://nats"
        resources: {}
status: {}
