apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/microservices-store-449702/registry-image/payments-ms-prod
        name: payments-ms-prod
        env:
        - name: PORT
          value: "8003"
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:8003/api/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:8003/api/payments/cancel"
        - name: STRIPE_ENDPOINTSECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: STRIPE_ENDPOINTSECRET
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: STRIPE_SECRET 
        - name: NATS_SERVERS
          value: "nats://nats"
        resources: {}
status: {}
