apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-webhook
  name: payments-webhook
spec:
  ports:
  - name: "8003"
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
